# A workflow to check generating the HTML lists works

name: LWG issues CI

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Compile binary programs
      run: make pgms

    - name: Generate HTML lists
      run: make lists
